<a href="https://colab.research.google.com/github/charmi-devisetty/2303A51314_PnS/blob/main/Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

In [20]:
#print array
A=np.array([[9,10,11],[15,16,17],[21,22,23],[35,36,37]])
print(A)

[[ 9 10 11]
 [15 16 17]
 [21 22 23]
 [35 36 37]]


In [14]:
print(A[0,:])
print(A[1,:])
print(A[2,:])
print(A[3,:])

[ 9 10 11]
[15 16 17]
[21 22 23]
[35 36 37]


In [22]:
#print 3rd column
print(A[:,2])

[11 17 23 37]


In [23]:
#print 3rd row
print(A[2,:])

[21 22 23]


In [16]:
#print size
print(np.size(A))

12


In [24]:
#print element
print(A[2,2])

23
